# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9c8c24776eb6963f70fe887567c7a014"
name = "checkout-extensibility"
handle = "checkout-extensibility-5"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
dev_store_url = "bsrxonlinetesting.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_checkouts,read_customers,read_orders,read_products,read_shipping,write_checkouts,write_customers,write_orders,write_products,write_shipping"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
